# Generated by Django 3.2.14 on 2022-07-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ManyToManyField(through="jobs.Job", to="jobs.Company"),
        ),
    ]
