# Generated by Django 3.2.15 on 2022-09-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_id",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
